# Generated by Django 4.2.4 on 2024-10-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher_title', models.CharField(max_length=255)),
                ('publisher_url', models.URLField()),
                ('alignment', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
