# Generated by Django 4.2.4 on 2024-10-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_newsarticle_topic_delete_masterarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('alignment', models.CharField(max_length=50)),
                ('replace_words', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='publisher_title',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='publisher_url',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='section',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticias.periodico'),
        ),
    ]
