# Generated by Django 4.2.4 on 2024-10-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_periodico_remove_newsarticle_alignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodico',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
